# Generated by Django 4.0.3 on 2022-03-08 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_book_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='picture',
        ),
    ]
